version: "3.8"
services:
  db:
    image: mysql:8.0.26
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - data_base:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=microservice_db
      - MYSQL_ROOT_PASSWORD=LargaNewerSleep5!
    ports:
      - "3306:3306"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
        - ./:/code_larga_microserv
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:5.1.1
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  data_base: