# Generated by Django 3.2.5 on 2022-06-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуален'),
        ),
    ]
