# Generated by Django 3.2.5 on 2022-06-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_counterparty_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignActStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название этапа актирования')),
                ('date', models.DateField(verbose_name='Дата акирования')),
                ('days_for_payment', models.IntegerField(verbose_name='Кол-во календарных дней на оплату после актирования')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Сумма (без НДС)')),
                ('sum_with_nds', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Сумма (c НДС)')),
                ('be_nds', models.BooleanField(blank=True, default=False, null=True, verbose_name='+НДС')),
                ('signed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписан')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Этап актироания по договору',
                'verbose_name_plural': 'Этапы актирования по договорам',
                'ordering': ('title',),
            },
        ),
    ]
