# Generated by Django 3.2.5 on 2022-06-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_signactstages'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstages',
            name='signActStages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.signactstages', verbose_name='Этап актиования'),
        ),
    ]
